all:

include ../kaldi.mk

TESTFILES = sdtw-utils-test fast-pattern-searcher-test

OBJFILES = fast-pattern-searcher.o

LIBNAME = kaldi-sdtw

ADDLIBS = ../util/kaldi-util.a ../base/kaldi-base.a ../matrix/kaldi-matrix.a 

include ../makefiles/default_rules.mk