
all:

EXTRA_CXXFLAGS = -Wno-sign-compare
include ../kaldi.mk

BINFILES = fast-sdtw

OBJFILES =

TESTFILES =

ADDLIBS = ../sdtw/kaldi-sdtw.a ../util/kaldi-util.a ../base/kaldi-base.a ../matrix/kaldi-matrix.a

include ../makefiles/default_rules.mk

